/**
 * Dev-mock sample data: usage mode — provider catalog, subscriptions with
 * realistic quota/balance shapes, alerts, and the dashboard summary. Consumed
 * by ./usage.ts.
 */

const nowSec = () => Math.floor(Date.now() / 1000);
const days = (n: number) => n * 86_400;

export const USAGE_CATALOG = [
  {
    id: "cursor",
    display_name: "Cursor",
    description: "AI Code Editor",
    tier: "o-auth",
    auth_modes: ["o-auth"],
    brand_color: "00E5BC",
    default_currency: "USD",
    subscription_url: "https://cursor.com/settings",
    warning: null,
    regions: [],
  },
  {
    id: "codex",
    display_name: "Codex",
    description: "OpenAI Codex CLI",
    tier: "o-auth",
    auth_modes: ["o-auth"],
    brand_color: "10A37F",
    default_currency: "USD",
    subscription_url: "https://chat.openai.com/codex",
    warning: null,
    regions: [],
  },
  {
    id: "antigravity",
    display_name: "Antigravity",
    description: "Google AI IDE",
    tier: "o-auth",
    auth_modes: ["o-auth"],
    brand_color: "4285F4",
    default_currency: "USD",
    subscription_url: "https://antigravity.google",
    warning: null,
    regions: [],
  },
  {
    id: "xai",
    display_name: "Grok",
    description: "xAI Grok CLI",
    tier: "o-auth",
    auth_modes: ["o-auth"],
    brand_color: "111111",
    default_currency: "USD",
    subscription_url: "https://x.ai",
    warning: null,
    regions: [],
  },
  {
    id: "anthropic",
    display_name: "Claude",
    description: "Anthropic Claude Code",
    tier: "o-auth",
    auth_modes: ["o-auth"],
    brand_color: "D97757",
    default_currency: "USD",
    subscription_url: "https://claude.ai/settings/usage",
    warning:
      "Claude 额度读取 Claude Code 自己的登录态（macOS 钥匙串 `Claude Code-credentials`，其它平台 `~/.claude/.credentials.json`）。请先在终端跑一次 `claude` 完成登录，再点下方按钮绑定；SkillStar 不会刷新或覆盖这份凭证。",
    regions: [],
  },
  {
    id: "deepseek",
    display_name: "DeepSeek",
    description: "API Key 余额",
    tier: "api-key",
    auth_modes: ["api-key"],
    brand_color: "1A56DB",
    default_currency: "CNY",
    subscription_url: "https://platform.deepseek.com/usage",
    warning: null,
    regions: [],
  },
  {
    id: "kimi",
    display_name: "Kimi",
    description: "Moonshot",
    tier: "api-key",
    auth_modes: ["api-key"],
    brand_color: "F5B400",
    default_currency: "CNY",
    subscription_url: "https://platform.moonshot.cn",
    warning: null,
    regions: [],
  },
  {
    id: "glm",
    display_name: "智谱 GLM",
    description: "Coding Plan",
    tier: "api-key",
    auth_modes: ["api-key"],
    brand_color: "4A90E2",
    default_currency: "CNY",
    subscription_url: "https://bigmodel.cn/usercenter/order",
    warning: null,
    regions: [],
  },
  {
    id: "minimax",
    display_name: "MiniMax",
    description: "Token Plan",
    tier: "api-key",
    auth_modes: ["api-key"],
    brand_color: "9333EA",
    default_currency: "CNY",
    subscription_url: "https://platform.minimaxi.com/user-center/basic-information/interface-key",
    warning: null,
    regions: [],
  },
  {
    id: "stepfun",
    display_name: "阶跃 Step",
    description: "账户余额 / 消费",
    tier: "cookie",
    auth_modes: ["cookie", "manual"],
    brand_color: "00B5A9",
    default_currency: "CNY",
    subscription_url: "https://platform.stepfun.com/account-overview",
    warning:
      "阶跃官方未提供余额查询 API：请使用 Cookie 模式，登录 platform.stepfun.com 后，从浏览器开发者工具复制包含 Oasis-Token 的 Cookie。",
    regions: [],
  },
  {
    id: "opencode",
    display_name: "OpenCode",
    description: "$10/月 Go 订阅 · Zen 按量付费",
    tier: "cookie",
    auth_modes: ["cookie", "manual"],
    brand_color: "6366F1",
    default_currency: "USD",
    subscription_url: "https://opencode.ai/workspace",
    warning:
      "OpenCode 官方 OAuth token 无法读取控制台用量；请使用 Cookie 模式，从 opencode.ai 控制台请求中复制 Cookie。",
    regions: [],
  },
];

function sub(over: Record<string, unknown>): Record<string, unknown> {
  return {
    plan_tier: null,
    monthly_price: null,
    currency: "USD",
    billing_cycle: "monthly",
    start_date: nowSec() - days(40),
    renew_date: nowSec() + days(12),
    auto_renew: true,
    has_credential: true,
    requires_reauth: false,
    is_active: true,
    manual_quota: null,
    note: null,
    sort_index: 0,
    created_at: nowSec() - days(40),
    updated_at: nowSec() - days(1),
    usage: null,
    ...over,
  };
}

export const USAGE_SUBSCRIPTIONS = [
  sub({
    id: "sub-cursor",
    catalog_id: "cursor",
    display_name: "Cursor Pro",
    auth_mode: "o-auth",
    plan_tier: "PRO",
    monthly_price: 20,
    currency: "USD",
    renew_date: nowSec() + days(3),
    sort_index: 0,
    usage: {
      subscription_id: "sub-cursor",
      fetched_at: nowSec() - 1800,
      plan_name: "PRO",
      hourly: null,
      weekly: null,
      // Included plan allowance (USD cents) + Auto/API percent breakdown.
      monthly: {
        label: "Total",
        used: 4653,
        total: 9495,
        percent: 49,
        reset_at: nowSec() + days(3),
        breakdown: [
          {
            label: "Auto + Composer",
            used: 51,
            total: 100,
            percent: 51,
            reset_at: null,
            breakdown: [],
          },
          {
            label: "API",
            used: 43,
            total: 100,
            percent: 43,
            reset_at: null,
            breakdown: [],
          },
        ],
      },
      balance: null,
      credits: [
        {
          credit_type: "cursor-bonus",
          credit_amount: "$20",
          minimum_credit_amount_for_usage: null,
        },
        {
          credit_type: "cursor-on-demand",
          credit_amount: "1200/5000",
          minimum_credit_amount_for_usage: null,
        },
      ],
      error: null,
      api_keys: [],
    },
  }),
  sub({
    id: "sub-codex",
    catalog_id: "codex",
    display_name: "ChatGPT Plus · Codex",
    auth_mode: "o-auth",
    plan_tier: "PLUS",
    monthly_price: 20,
    currency: "USD",
    sort_index: 1,
    usage: {
      subscription_id: "sub-codex",
      fetched_at: nowSec() - 3600,
      plan_name: "PLUS",
      hourly: {
        label: "5h",
        used: 38,
        total: 150,
        percent: 25,
        reset_at: nowSec() + 9000,
        breakdown: [],
      },
      weekly: {
        label: "本周",
        used: 1240,
        total: 4000,
        percent: 31,
        reset_at: nowSec() + days(5),
        breakdown: [],
      },
      monthly: null,
      balance: null,
      credits: [],
      error: null,
      api_keys: [],
    },
  }),
  sub({
    id: "sub-anthropic",
    catalog_id: "anthropic",
    display_name: "claude@example.com",
    auth_mode: "o-auth",
    plan_tier: "MAX",
    monthly_price: 100,
    currency: "USD",
    sort_index: 2,
    is_active: false,
    usage: {
      subscription_id: "sub-anthropic",
      fetched_at: nowSec() - 600,
      plan_name: "MAX",
      // Percent-only rate-limit windows: `used == percent`, `total == 100`.
      // Same shape Codex emits, so both cards read through `UsageMeter`.
      hourly: { label: "5h", used: 47, total: 100, percent: 47, reset_at: nowSec() + 7200, breakdown: [] },
      weekly: {
        label: "7d",
        used: 68,
        total: 100,
        percent: 68,
        reset_at: nowSec() + days(4),
        // `limits[].kind == "weekly_scoped"` — per-model weekly allowances.
        // Scoped limits share the parent's reset, so the fetcher strips their
        // redundant countdown rather than stacking three identical chips.
        breakdown: [
          { label: "Opus 5", used: 91, total: 100, percent: 91, breakdown: [] },
          { label: "Sonnet 5", used: 22, total: 100, percent: 22, breakdown: [] },
        ],
      },
      monthly: null,
      balance: null,
      credits: [],
      error: null,
      api_keys: [],
    },
  }),
  sub({
    id: "sub-xai",
    catalog_id: "xai",
    display_name: "Grok",
    auth_mode: "o-auth",
    plan_tier: "Grok",
    monthly_price: 20,
    currency: "USD",
    sort_index: 2,
    usage: {
      subscription_id: "sub-xai",
      fetched_at: nowSec() - 900,
      plan_name: "Grok",
      hourly: null,
      // Grok SuperGrok / Build: strict weekly pool (percent + reset only).
      // Month spend + on-demand cap as secondary credits (not a second quota bar).
      weekly: {
        label: "Weekly credits",
        used: 0,
        total: null,
        percent: 30,
        reset_at: nowSec() + days(4),
        breakdown: [],
      },
      monthly: null,
      balance: null,
      credits: [
        {
          credit_type: "grok-month-spend",
          credit_amount: "7006/20000",
          minimum_credit_amount_for_usage: null,
        },
        {
          credit_type: "grok-on-demand-cap",
          credit_amount: "$20",
          minimum_credit_amount_for_usage: null,
        },
      ],
      error: null,
      api_keys: [],
    },
  }),
  sub({
    id: "sub-deepseek",
    catalog_id: "deepseek",
    display_name: "DeepSeek 余额",
    auth_mode: "api-key",
    plan_tier: "PAYG",
    currency: "CNY",
    billing_cycle: "one-time",
    sort_index: 3,
    usage: {
      subscription_id: "sub-deepseek",
      fetched_at: nowSec() - 600,
      plan_name: null,
      hourly: null,
      weekly: null,
      monthly: null,
      balance: {
        currency: "CNY",
        total: 48.5,
        granted: 5,
        topped_up: 43.5,
        is_available: true,
      },
      credits: [{ credit_type: "deepseek-balance:USD", credit_amount: "2.00" }],
      error: null,
      api_keys: [],
    },
  }),
  sub({
    id: "sub-glm",
    catalog_id: "glm",
    display_name: "GLM Coding Plan",
    auth_mode: "api-key",
    plan_tier: "pro",
    currency: "CNY",
    requires_reauth: true,
    sort_index: 4,
    usage: {
      subscription_id: "sub-glm",
      fetched_at: nowSec() - 7200,
      plan_name: "lite",
      hourly: {
        label: "5h",
        used: 10_000_000,
        total: 40_000_000,
        percent: 25,
        reset_at: nowSec() + 7200,
        breakdown: [],
      },
      weekly: {
        label: "7d",
        used: 50_000_000,
        total: 200_000_000,
        percent: 25,
        reset_at: nowSec() + days(3),
        breakdown: [],
      },
      monthly: {
        label: "MCP",
        used: 100,
        total: 4000,
        percent: 2,
        reset_at: null,
        breakdown: [
          {
            label: "glm-mcp-search",
            used: 60,
            total: null,
            percent: null,
            reset_at: null,
            breakdown: [],
          },
          {
            label: "glm-mcp-web-read",
            used: 30,
            total: null,
            percent: null,
            reset_at: null,
            breakdown: [],
          },
        ],
      },
      balance: null,
      credits: [
        { credit_type: "glm-24h-tokens", credit_amount: "1250000" },
        { credit_type: "glm-24h-calls", credit_amount: "42" },
        { credit_type: "glm-model:glm-4.7", credit_amount: "600" },
        { credit_type: "glm-24h-network-search", credit_amount: "5" },
      ],
      error: "GLM 需要重新登录（凭证已过期）",
      api_keys: [],
    },
  }),
];

export const USAGE_ALERTS = [
  {
    id: "al-1",
    subscription_id: "sub-cursor",
    severity: "warning",
    kind: "renew-soon",
    message: "Cursor Pro 将在 3 天后续费",
  },
  {
    id: "al-2",
    subscription_id: "sub-glm",
    severity: "danger",
    kind: "quota-critical",
    message: "GLM 5 小时额度已用 90%",
  },
  {
    id: "al-3",
    subscription_id: "sub-glm",
    severity: "warning",
    kind: "needs-reauth",
    message: "GLM 需要重新登录",
  },
];

export const USAGE_SUMMARY = {
  monthly_spend: [{ currency: "USD", amount: 40 }],
  total_subscriptions: USAGE_SUBSCRIPTIONS.length,
  alert_count: USAGE_ALERTS.length,
  reauth_count: 1,
};
