version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
    open-pull-requests-limit: 4
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "03:00"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "03:00"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "security"
