[package]
name = "skillstar-skills"
version = "0.1.0"
edition = "2024"
rust-version = "1.94.1"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
skillstar-core = { version = "0.1.0", path = "../skillstar-core" }
gix = { workspace = true }
serde_yaml = { workspace = true }
dirs = { workspace = true }
flate2 = { workspace = true }
sha2 = { workspace = true }
tar = { workspace = true }
toml = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }
base64.workspace = true
scraper = "0.27.0"

[dev-dependencies]
tempfile = { workspace = true }

[target."cfg(windows)".dependencies]
junction = { workspace = true }
