[package]
name = "skillstar-ai"
version = "0.1.0"
edition = "2024"
rust-version = "1.94.1"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, features = ["rustls", "json", "stream"] }
reqwest_012 = { package = "reqwest", version = "0.12", default-features = false, features = ["rustls-tls", "json", "stream"] }
tracing = { workspace = true }
regex = { workspace = true }
machine-uid = { workspace = true }
aes-gcm = { workspace = true }
base64 = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }
chrono = { workspace = true }
lazy_static = { workspace = true }
async-openai = { version = "0.27", features = ["rustls"] }
futures-util = "0.3.32"
futures = { workspace = true }
comrak = "0.37"
quick-xml = "0.37"
blake3 = "1.5"
skillstar-core = { version = "0.1.0", path = "../skillstar-core" }
skillstar-models = { version = "0.1.0", path = "../skillstar-models" }
rusqlite = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
