//! Local decision model (AgentJev-0.6B) types.
//!
//! Every type here is generated by ts-rs from `skillstar-decision` — see
//! `src/types/generated/` and the `types:gen` script. Nothing is hand-mirrored:
//! the answer shape is the contract the model actually returns, and a manual
//! copy would drift the moment the head changes.

export type { DecisionAnswer } from "./generated/DecisionAnswer";
export type { DecisionDistributionEntry } from "./generated/DecisionDistributionEntry";
export type { DecisionDownloadProgress } from "./generated/DecisionDownloadProgress";
export type { DecisionEncodedPath } from "./generated/DecisionEncodedPath";
export type { DecisionEngineInfo } from "./generated/DecisionEngineInfo";
export type { DecisionModelFileStatus } from "./generated/DecisionModelFileStatus";
export type { DecisionModelState } from "./generated/DecisionModelState";
export type { DecisionModelStatus } from "./generated/DecisionModelStatus";
export type { DecisionOutcome } from "./generated/DecisionOutcome";
export type { DecisionQuestionKind } from "./generated/DecisionQuestionKind";
export type { DecisionRequestAnswers } from "./generated/DecisionRequestAnswers";
export type { DecisionTemperatures } from "./generated/DecisionTemperatures";
export type { DecisionUsage } from "./generated/DecisionUsage";
