//! Post-clone setup hook storage and execution.
//!
//! Stores a shell script per skill that was generated by an external Agent via
//! ACP.  On skill updates the script is automatically re-executed so the repo
//! stays in a usable state.
//!
//! ## Storage layout
//!
//! ```text
//! ~/.skillstar/setup-hooks/
//! ├── gstack.json   # metadata (last run time, result, output)
//! └── gstack.sh     # shell script
//! ```

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use tracing::{debug, error, info, warn};

use super::path_env;
use super::paths;

// ── Data Types ──────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum HookResult {
    Success,
    Failed,
    Timeout,
}

/// Metadata persisted alongside each hook script.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct HookMeta {
    skill_name: String,
    #[serde(default)]
    last_run: Option<String>,
    #[serde(default)]
    last_result: Option<HookResult>,
    #[serde(default)]
    last_output: Option<String>,
}

/// Full hook data returned to the frontend.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SetupHook {
    pub skill_name: String,
    pub script: String,
    #[serde(default)]
    pub last_run: Option<String>,
    #[serde(default)]
    pub last_result: Option<HookResult>,
    #[serde(default)]
    pub last_output: Option<String>,
}

/// Output from executing a hook.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HookRunOutput {
    pub result: HookResult,
    pub stdout: String,
    pub stderr: String,
    pub duration_ms: u64,
}

// ── Path Helpers ────────────────────────────────────────────────────

fn hooks_dir() -> PathBuf {
    paths::setup_hooks_dir()
}

fn meta_path(skill_name: &str) -> PathBuf {
    hooks_dir().join(format!("{}.json", skill_name))
}

fn script_path(skill_name: &str) -> PathBuf {
    hooks_dir().join(format!("{}.sh", skill_name))
}

// ── CRUD ────────────────────────────────────────────────────────────

/// Save a setup hook script (typically returned by an ACP Agent).
pub fn save_hook(skill_name: &str, script: &str) -> Result<()> {
    let dir = hooks_dir();
    std::fs::create_dir_all(&dir).context("Failed to create setup-hooks directory")?;

    std::fs::write(script_path(skill_name), script).context("Failed to write setup hook script")?;

    let meta = load_meta(skill_name).unwrap_or_else(|| HookMeta {
        skill_name: skill_name.to_string(),
        last_run: None,
        last_result: None,
        last_output: None,
    });
    save_meta(&meta)?;

    info!(target: "setup_hook", skill = %skill_name, "saved setup hook");
    Ok(())
}

/// Load the full hook (meta + script content).
pub fn load_hook(skill_name: &str) -> Option<SetupHook> {
    let sp = script_path(skill_name);
    let script = std::fs::read_to_string(&sp).ok()?;
    let meta = load_meta(skill_name)?;

    Some(SetupHook {
        skill_name: meta.skill_name,
        script,
        last_run: meta.last_run,
        last_result: meta.last_result,
        last_output: meta.last_output,
    })
}

/// Check whether a hook exists for the given skill.
pub fn has_hook(skill_name: &str) -> bool {
    script_path(skill_name).exists()
}

/// Delete a setup hook.
pub fn delete_hook(skill_name: &str) -> Result<()> {
    let mp = meta_path(skill_name);
    let sp = script_path(skill_name);
    if mp.exists() {
        std::fs::remove_file(&mp).context("Failed to remove hook metadata")?;
    }
    if sp.exists() {
        std::fs::remove_file(&sp).context("Failed to remove hook script")?;
    }
    info!(target: "setup_hook", skill = %skill_name, "deleted setup hook");
    Ok(())
}

// ── Execution ───────────────────────────────────────────────────────

/// Maximum time a setup hook is allowed to run (5 minutes).
const HOOK_TIMEOUT_SECS: u64 = 300;

/// Execute the setup hook for a skill.
///
/// The script runs in the resolved repo root directory.
pub async fn execute_hook(skill_name: &str) -> Result<HookRunOutput> {
    let sp = script_path(skill_name);
    let script = std::fs::read_to_string(&sp).context("Setup hook script not found")?;

    // Resolve skill directory → repo root
    let skills_dir = paths::hub_skills_dir();
    let skill_path = skills_dir.join(skill_name);
    let work_dir = resolve_work_dir(&skill_path);

    info!(
        target: "setup_hook",
        skill = %skill_name,
        dir = %work_dir.display(),
        "executing setup hook"
    );

    let start = std::time::Instant::now();

    let output = tokio::time::timeout(
        std::time::Duration::from_secs(HOOK_TIMEOUT_SECS),
        tokio::task::spawn_blocking({
            let work_dir = work_dir.clone();
            let script = script.clone();
            move || run_script_blocking(&work_dir, &script)
        }),
    )
    .await;

    let duration_ms = start.elapsed().as_millis() as u64;

    let run_output = match output {
        Ok(Ok(Ok(mut out))) => {
            out.duration_ms = duration_ms;
            out
        }
        Ok(Ok(Err(e))) => HookRunOutput {
            result: HookResult::Failed,
            stdout: String::new(),
            stderr: e.to_string(),
            duration_ms,
        },
        Ok(Err(e)) => HookRunOutput {
            result: HookResult::Failed,
            stdout: String::new(),
            stderr: format!("Task panicked: {}", e),
            duration_ms,
        },
        Err(_) => HookRunOutput {
            result: HookResult::Timeout,
            stdout: String::new(),
            stderr: format!("Setup hook timed out after {}s", HOOK_TIMEOUT_SECS),
            duration_ms,
        },
    };

    // Persist run result
    let combined = format!("{}\n{}", run_output.stdout, run_output.stderr);
    let truncated = if combined.len() > 4096 {
        combined[..4096].to_string()
    } else {
        combined
    };

    if let Some(mut m) = load_meta(skill_name) {
        m.last_run = Some(chrono::Utc::now().to_rfc3339());
        m.last_result = Some(run_output.result.clone());
        m.last_output = Some(truncated);
        let _ = save_meta(&m);
    }

    match &run_output.result {
        HookResult::Success => {
            info!(target: "setup_hook", skill = %skill_name, duration_ms, "setup hook succeeded");
        }
        HookResult::Failed => {
            error!(target: "setup_hook", skill = %skill_name, duration_ms, "setup hook failed");
        }
        HookResult::Timeout => {
            warn!(target: "setup_hook", skill = %skill_name, duration_ms, "setup hook timed out");
        }
    }

    Ok(run_output)
}

/// Run the hook automatically if one exists (called after update_skill).
pub async fn run_if_exists(skill_name: &str) -> Option<HookRunOutput> {
    if !has_hook(skill_name) {
        debug!(target: "setup_hook", skill = %skill_name, "no setup hook, skipping");
        return None;
    }
    match execute_hook(skill_name).await {
        Ok(output) => Some(output),
        Err(e) => {
            error!(target: "setup_hook", skill = %skill_name, error = %e, "setup hook execution error");
            None
        }
    }
}

// ── Internal helpers ────────────────────────────────────────────────

fn load_meta(skill_name: &str) -> Option<HookMeta> {
    let mp = meta_path(skill_name);
    let content = std::fs::read_to_string(&mp).ok()?;
    serde_json::from_str::<HookMeta>(&content)
        .map_err(|e| warn!(target: "setup_hook", path = %mp.display(), error = %e, "bad hook meta"))
        .ok()
}

fn save_meta(meta: &HookMeta) -> Result<()> {
    let dir = hooks_dir();
    std::fs::create_dir_all(&dir)?;
    let content = serde_json::to_string_pretty(meta)?;
    std::fs::write(meta_path(&meta.skill_name), content)?;
    Ok(())
}

/// Resolve the working directory for hook execution.
///
/// If the skill is a symlink into `.repos/<cache>/subfolder`, return the
/// `.repos/<cache>` root so the hook runs at the repo root.  Otherwise
/// return the canonicalized skill directory.
fn resolve_work_dir(skill_path: &Path) -> PathBuf {
    let Ok(canonical) = std::fs::canonicalize(skill_path) else {
        return skill_path.to_path_buf();
    };

    let repos_cache = paths::repos_cache_dir();
    if !canonical.starts_with(&repos_cache) {
        return canonical;
    }

    // Structure: .repos/<cache-name>/optional/subfolder
    // We want: .repos/<cache-name>
    if let Ok(relative) = canonical.strip_prefix(&repos_cache) {
        if let Some(first) = relative.components().next() {
            return repos_cache.join(first);
        }
    }
    canonical
}

/// Execute a shell script in a given working directory (blocking).
fn run_script_blocking(work_dir: &Path, script: &str) -> Result<HookRunOutput> {
    #[cfg(unix)]
    let shell = "bash";
    #[cfg(windows)]
    let shell = "cmd";

    let mut cmd = path_env::command_with_path(shell);

    #[cfg(unix)]
    cmd.arg("-c").arg(script);
    #[cfg(windows)]
    cmd.arg("/C").arg(script);

    cmd.current_dir(work_dir);

    let output = cmd
        .output()
        .context("Failed to execute setup hook script")?;

    Ok(HookRunOutput {
        result: if output.status.success() {
            HookResult::Success
        } else {
            HookResult::Failed
        },
        stdout: String::from_utf8_lossy(&output.stdout).to_string(),
        stderr: String::from_utf8_lossy(&output.stderr).to_string(),
        duration_ms: 0,
    })
}

// ── Rebuild Skills ─────────────────────────────────────────────────

/// A skill discovered inside a `skills-rebuild/` directory.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DiscoveredRebuildSkill {
    /// Skill name (directory name under skills-rebuild/)
    pub name: String,
    /// Absolute path to the skill directory
    pub path: String,
    /// Whether this skill is already installed in the hub
    pub already_installed: bool,
}

/// Scan a `skills-rebuild/` directory inside a repo cache.
///
/// Returns a list of skills found, each being a subdirectory that contains
/// a `SKILL.md` file.
pub fn scan_rebuild_dir(skill_name: &str) -> Vec<DiscoveredRebuildSkill> {
    let skills_dir = paths::hub_skills_dir();
    let skill_path = skills_dir.join(skill_name);
    let work_dir = resolve_work_dir(&skill_path);
    let rebuild_dir = work_dir.join("skills-rebuild");

    if !rebuild_dir.exists() {
        debug!(
            target: "setup_hook",
            skill = %skill_name,
            path = %rebuild_dir.display(),
            "no skills-rebuild directory found"
        );
        return Vec::new();
    }

    let mut result = Vec::new();
    let entries = match std::fs::read_dir(&rebuild_dir) {
        Ok(e) => e,
        Err(e) => {
            warn!(
                target: "setup_hook",
                path = %rebuild_dir.display(),
                error = %e,
                "failed to read skills-rebuild directory"
            );
            return Vec::new();
        }
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.') {
            continue;
        }
        // Must contain a SKILL.md
        if !path.join("SKILL.md").exists() {
            debug!(
                target: "setup_hook",
                dir = %name,
                "skipping rebuild dir entry without SKILL.md"
            );
            continue;
        }
        let already_installed = skills_dir.join(&name).exists();
        result.push(DiscoveredRebuildSkill {
            name,
            path: path.to_string_lossy().to_string(),
            already_installed,
        });
    }

    result.sort_by(|a, b| a.name.to_lowercase().cmp(&b.name.to_lowercase()));

    info!(
        target: "setup_hook",
        skill = %skill_name,
        count = result.len(),
        "scanned skills-rebuild directory"
    );

    result
}

/// Rebuild skill symlinks from a `skills-rebuild/` directory.
///
/// After the setup hook has produced `skills-rebuild/` inside the repo cache,
/// this function:
/// 1. Removes the old monolithic root-level symlink (e.g. `skills/gstack`)
/// 2. Creates individual symlinks for each skill in `skills-rebuild/`
/// 3. Updates the lockfile for each new skill entry
///
/// Returns the list of newly installed skill names.
pub fn rebuild_skills_from_repo(skill_name: &str, repo_url: &str) -> Result<Vec<String>> {
    let skills_dir = paths::hub_skills_dir();
    let skill_path = skills_dir.join(skill_name);
    let work_dir = resolve_work_dir(&skill_path);
    let rebuild_dir = work_dir.join("skills-rebuild");

    if !rebuild_dir.exists() || !rebuild_dir.is_dir() {
        return Err(anyhow::anyhow!(
            "skills-rebuild directory not found at {}",
            rebuild_dir.display()
        ));
    }

    // Scan the rebuild directory
    let discovered = scan_rebuild_dir(skill_name);
    if discovered.is_empty() {
        return Err(anyhow::anyhow!(
            "skills-rebuild directory is empty or contains no valid skills"
        ));
    }

    info!(
        target: "setup_hook",
        skill = %skill_name,
        count = discovered.len(),
        "rebuilding skills from skills-rebuild/"
    );

    // Remove the old monolithic root-level symlink
    if skill_path.symlink_metadata().is_ok() {
        if let Err(e) = paths::remove_symlink(&skill_path) {
            warn!(
                target: "setup_hook",
                skill = %skill_name,
                error = %e,
                "failed to remove old root-level symlink, trying remove_dir_all"
            );
            let _ = std::fs::remove_dir_all(&skill_path);
        }
        info!(
            target: "setup_hook",
            skill = %skill_name,
            "removed old root-level symlink"
        );
    }

    // Lock lockfile for batch update
    let lock_mutex = super::lockfile::get_mutex();
    let _lock = lock_mutex
        .lock()
        .map_err(|_| anyhow::anyhow!("Lockfile mutex poisoned"))?;
    let lock_path = super::lockfile::lockfile_path();
    let mut lf = super::lockfile::Lockfile::load(&lock_path).unwrap_or_default();

    // Remove the old monolithic lockfile entry
    lf.remove(skill_name);

    let mut installed_names = Vec::new();

    for skill in &discovered {
        let dest = skills_dir.join(&skill.name);
        let source = PathBuf::from(&skill.path);

        // Skip if already installed from a different source
        if dest.symlink_metadata().is_ok() {
            info!(
                target: "setup_hook",
                skill = %skill.name,
                "already installed, replacing symlink for rebuild"
            );
            let _ = paths::remove_symlink(&dest);
            // If it's a real directory (not symlink), remove it too
            if dest.exists() {
                let _ = std::fs::remove_dir_all(&dest);
            }
        }

        // Create symlink: skills/<name> → skills-rebuild/<name>
        paths::create_symlink(&source, &dest)
            .with_context(|| format!("Failed to symlink {:?} → {:?}", source, dest))?;

        // Compute the folder_path relative to the repo cache root
        let folder_path = if let Ok(rel) = source.strip_prefix(&work_dir) {
            let rel_str = rel.to_string_lossy().to_string();
            let clean = rel_str
                .trim_matches(|c: char| c == '/' || c == '\\')
                .to_string();
            if clean.is_empty() { None } else { Some(clean) }
        } else {
            None
        };

        // Update lockfile
        lf.upsert(super::lockfile::LockEntry {
            name: skill.name.clone(),
            git_url: repo_url.to_string(),
            tree_hash: String::new(), // Will be recomputed on next update check
            installed_at: chrono::Utc::now().to_rfc3339(),
            source_folder: folder_path,
        });

        installed_names.push(skill.name.clone());

        info!(
            target: "setup_hook",
            skill = %skill.name,
            source = %source.display(),
            dest = %dest.display(),
            "symlinked rebuild skill"
        );
    }

    let _ = lf.save(&lock_path);

    // Invalidate installed skill cache so the UI refreshes
    super::installed_skill::invalidate_cache();

    // Invalidate security scan cache for all newly installed skills
    for name in &installed_names {
        super::security_scan::invalidate_skill_cache(name);
    }

    info!(
        target: "setup_hook",
        original = %skill_name,
        count = installed_names.len(),
        names = ?installed_names,
        "rebuild complete"
    );

    Ok(installed_names)
}

// ── Tests ───────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn hook_crud_roundtrip() {
        let _lock = crate::core::test_env_lock().lock().unwrap();

        let temp = std::env::temp_dir().join("skillstar_test_hook_crud");
        let _ = fs::remove_dir_all(&temp);
        fs::create_dir_all(&temp).unwrap();

        unsafe { std::env::set_var("SKILLSTAR_DATA_DIR", temp.to_str().unwrap()) };

        let name = "test-hook-skill";
        let script = "#!/bin/bash\necho hello";

        save_hook(name, script).unwrap();
        assert!(has_hook(name));

        let hook = load_hook(name).unwrap();
        assert_eq!(hook.script, script);
        assert_eq!(hook.skill_name, name);

        delete_hook(name).unwrap();
        assert!(!has_hook(name));

        let _ = fs::remove_dir_all(&temp);
        unsafe { std::env::remove_var("SKILLSTAR_DATA_DIR") };
    }

    #[test]
    fn scan_rebuild_dir_finds_skills_with_skill_md() {
        let _lock = crate::core::test_env_lock().lock().unwrap();

        let temp = std::env::temp_dir().join("skillstar_test_scan_rebuild");
        let _ = fs::remove_dir_all(&temp);

        // Create fake hub structure
        let hub = temp.join(".agents");
        let skills_dir = hub.join("skills");
        let repos_dir = hub.join(".repos");
        let repo_cache = repos_dir.join("test--multi-skill");
        let rebuild_dir = repo_cache.join("skills-rebuild");

        fs::create_dir_all(&skills_dir).unwrap();
        fs::create_dir_all(&rebuild_dir).unwrap();

        // Create fake skills in skills-rebuild/
        for name in &["skill-alpha", "skill-beta", "no-skillmd"] {
            let dir = rebuild_dir.join(name);
            fs::create_dir_all(&dir).unwrap();
            if *name != "no-skillmd" {
                fs::write(
                    dir.join("SKILL.md"),
                    format!("---\nname: {}\n---\n# {}", name, name),
                )
                .unwrap();
            }
        }

        // Create a monolithic symlink: skills/multi-skill → .repos/test--multi-skill
        unsafe { std::env::set_var("SKILLSTAR_HUB_DIR", hub.to_str().unwrap()) };
        paths::create_symlink(&repo_cache, &skills_dir.join("multi-skill")).unwrap();

        // Scan
        let result = scan_rebuild_dir("multi-skill");

        assert_eq!(result.len(), 2, "should find 2 skills (not no-skillmd)");
        assert!(result.iter().any(|s| s.name == "skill-alpha"));
        assert!(result.iter().any(|s| s.name == "skill-beta"));
        assert!(!result.iter().any(|s| s.name == "no-skillmd"));

        let _ = fs::remove_dir_all(&temp);
        unsafe { std::env::remove_var("SKILLSTAR_HUB_DIR") };
    }

    #[test]
    fn scan_rebuild_dir_returns_empty_when_no_rebuild_dir() {
        let _lock = crate::core::test_env_lock().lock().unwrap();

        let temp = std::env::temp_dir().join("skillstar_test_scan_rebuild_empty");
        let _ = fs::remove_dir_all(&temp);

        let hub = temp.join(".agents");
        let skills_dir = hub.join("skills");
        let repos_dir = hub.join(".repos");
        let repo_cache = repos_dir.join("test--no-rebuild");

        fs::create_dir_all(&skills_dir).unwrap();
        fs::create_dir_all(&repo_cache).unwrap();

        unsafe { std::env::set_var("SKILLSTAR_HUB_DIR", hub.to_str().unwrap()) };
        paths::create_symlink(&repo_cache, &skills_dir.join("no-rebuild")).unwrap();

        let result = scan_rebuild_dir("no-rebuild");
        assert!(
            result.is_empty(),
            "should be empty when no skills-rebuild/ dir"
        );

        let _ = fs::remove_dir_all(&temp);
        unsafe { std::env::remove_var("SKILLSTAR_HUB_DIR") };
    }

    #[test]
    fn rebuild_skills_creates_symlinks_and_removes_old() {
        let _lock = crate::core::test_env_lock().lock().unwrap();

        let temp = std::env::temp_dir().join("skillstar_test_rebuild_apply");
        let _ = fs::remove_dir_all(&temp);

        let hub = temp.join(".agents");
        let skills_dir = hub.join("skills");
        let repos_dir = hub.join(".repos");
        let repo_cache = repos_dir.join("owner--myrepo");
        let rebuild_dir = repo_cache.join("skills-rebuild");

        fs::create_dir_all(&skills_dir).unwrap();
        fs::create_dir_all(&rebuild_dir).unwrap();

        // Create fake skills in skills-rebuild/
        for name in &["webapp", "cli-tool"] {
            let dir = rebuild_dir.join(name);
            fs::create_dir_all(&dir).unwrap();
            fs::write(
                dir.join("SKILL.md"),
                format!("---\nname: {}\n---\n# {}", name, name),
            )
            .unwrap();
        }

        // Set up environment
        unsafe { std::env::set_var("SKILLSTAR_DATA_DIR", temp.to_str().unwrap()) };
        unsafe { std::env::set_var("SKILLSTAR_HUB_DIR", hub.to_str().unwrap()) };

        // Create lockfile dir
        fs::create_dir_all(hub.clone()).unwrap();

        // Create the old monolithic symlink
        paths::create_symlink(&repo_cache, &skills_dir.join("myrepo")).unwrap();
        assert!(
            skills_dir.join("myrepo").exists(),
            "old symlink should exist"
        );

        // Apply rebuild
        let result = rebuild_skills_from_repo("myrepo", "https://github.com/owner/myrepo.git");
        assert!(result.is_ok(), "rebuild should succeed: {:?}", result);

        let installed = result.unwrap();
        assert_eq!(installed.len(), 2);
        assert!(installed.contains(&"webapp".to_string()));
        assert!(installed.contains(&"cli-tool".to_string()));

        // The old monolithic symlink should be gone
        assert!(
            !skills_dir.join("myrepo").symlink_metadata().is_ok(),
            "old monolithic symlink should be removed"
        );

        // Individual symlinks should exist
        assert!(
            skills_dir.join("webapp").exists(),
            "webapp symlink should exist"
        );
        assert!(
            skills_dir.join("cli-tool").exists(),
            "cli-tool symlink should exist"
        );

        // Verify they point to the right place
        let webapp_target = fs::read_link(skills_dir.join("webapp")).unwrap();
        assert!(
            webapp_target
                .to_string_lossy()
                .contains("skills-rebuild/webapp"),
            "webapp should point to skills-rebuild/webapp"
        );

        let _ = fs::remove_dir_all(&temp);
        unsafe { std::env::remove_var("SKILLSTAR_DATA_DIR") };
        unsafe { std::env::remove_var("SKILLSTAR_HUB_DIR") };
    }
}
