import {
  AmpColor,
  AntigravityColor,
  ClaudeCodeColor,
  ClineMono,
  CodeBuddyColor,
  CodexColor,
  CursorMono,
  DeepSeekColor,
  DevinColor,
  GeminiCLIColor,
  GithubCopilotMono,
  GooseMono,
  GrokMono,
  HermesAgentMono,
  IBMMono,
  InferenceMono,
  JunieColor,
  KiloCodeMono,
  KimiMono,
  KiroColor,
  LobeHubMono,
  MCPMono,
  MistralColor,
  OpenClawColor,
  OpenCodeMono,
  OpenHandsColor,
  PiMono,
  QoderColor,
  QwenColor,
  ReplitColor,
  RooCodeMono,
  SnowflakeColor,
  TraeColor,
  WindsurfMono,
  ZAIMono,
  ZencoderColor,
  type LobeIconComponent,
} from "./lobe";

/**
 * One icon projection for the synchronized built-in Agent registry.
 * Unknown brands intentionally use LobeHub's generic glyph so built-ins never
 * fall back to deleted local SVG assets.
 */
export const AGENT_ICON_BY_ID: Record<string, LobeIconComponent> = {
  "aider-desk": LobeHubMono,
  amp: AmpColor,
  antigravity: AntigravityColor,
  "antigravity-cli": AntigravityColor,
  astrbot: LobeHubMono,
  "autohand-code": LobeHubMono,
  augment: LobeHubMono,
  bob: IBMMono,
  claude: ClaudeCodeColor,
  openclaw: OpenClawColor,
  cline: ClineMono,
  "codearts-agent": LobeHubMono,
  codebuddy: CodeBuddyColor,
  codemaker: LobeHubMono,
  codestudio: LobeHubMono,
  codex: CodexColor,
  "command-code": LobeHubMono,
  continue: LobeHubMono,
  cortex: SnowflakeColor,
  crush: LobeHubMono,
  cursor: CursorMono,
  deepagents: LobeHubMono,
  deepseek: DeepSeekColor,
  devin: DevinColor,
  dexto: LobeHubMono,
  droid: LobeHubMono,
  eve: LobeHubMono,
  firebender: LobeHubMono,
  forgecode: LobeHubMono,
  "gemini-cli": GeminiCLIColor,
  "github-copilot": GithubCopilotMono,
  goose: GooseMono,
  hermes: HermesAgentMono,
  "inference-sh": InferenceMono,
  jazz: LobeHubMono,
  junie: JunieColor,
  "iflow-cli": LobeHubMono,
  kilo: KiloCodeMono,
  "kimi-code-cli": KimiMono,
  kiro: KiroColor,
  kode: LobeHubMono,
  lingma: LobeHubMono,
  loaf: LobeHubMono,
  mcpjam: MCPMono,
  "mistral-vibe": MistralColor,
  moxby: LobeHubMono,
  mux: LobeHubMono,
  neovate: LobeHubMono,
  omp: LobeHubMono,
  opencode: OpenCodeMono,
  openhands: OpenHandsColor,
  ona: LobeHubMono,
  pi: PiMono,
  qoder: QoderColor,
  "qoder-cn": QoderColor,
  "qwen-code": QwenColor,
  replit: ReplitColor,
  reasonix: LobeHubMono,
  roo: RooCodeMono,
  rovodev: LobeHubMono,
  "tabnine-cli": LobeHubMono,
  terramind: LobeHubMono,
  tinycloud: LobeHubMono,
  trae: TraeColor,
  "trae-cn": TraeColor,
  warp: LobeHubMono,
  windsurf: WindsurfMono,
  zed: LobeHubMono,
  zcode: ZAIMono,
  zencoder: ZencoderColor,
  zenflow: ZencoderColor,
  pochi: LobeHubMono,
  promptscript: LobeHubMono,
  adal: LobeHubMono,
  universal: LobeHubMono,
  grok: GrokMono,
};

export function getAgentIcon(agentId: string): LobeIconComponent {
  return AGENT_ICON_BY_ID[agentId] ?? LobeHubMono;
}
