[package]
name = "skillstar-agents"
version = "0.1.0"
edition = "2024"
rust-version = "1.94.1"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
skillstar-core = { version = "0.1.0", path = "../skillstar-core" }
toml = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
