[package]
name = "skillstar-learning"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
chrono = { workspace = true }
regex = { workspace = true }
scraper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
skillstar-core = { path = "../skillstar-core" }
uuid = { workspace = true, features = ["serde"] }

[dev-dependencies]
tempfile = { workspace = true }
