[package]
name = "skillstar-models"
version = "0.1.0"
edition = "2024"
rust-version = "1.94.1"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt", "time", "macros"] }
reqwest = { workspace = true, features = ["rustls", "json", "stream"] }
tracing = { workspace = true }
chrono = { workspace = true }
lazy_static = { workspace = true }
dirs = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
toml = { workspace = true }
skillstar-core = { version = "0.1.0", path = "../skillstar-core" }
skillstar-providers = { version = "0.1.0", path = "../skillstar-providers" }
ts-rs = { workspace = true, features = ["serde-compat"] }

[dev-dependencies]
proptest = "1.11.0"
tempfile = { workspace = true }
