// Re-export barrel for the Usage feature's backend contract.
//
// Every shape below is GENERATED by ts-rs from Rust and lives in
// `src/types/generated/` — see `bun run types:gen` and
// `scripts/internal/check_generated_types.sh`, which fails the build when the
// committed output drifts from the source. Do not hand-write these shapes
// here; edit the Rust struct and regenerate.
//
//   - AuthMode, CatalogTier come from `skillstar_usage::catalog`.
//   - BillingCycle, ManualQuota, SubscriptionUsage (and its UsageWindow /
//     MonetaryBalance / CreditInfo / OpenCodeApiKey / DeepSeek* leaves),
//     AlertSeverity, AlertKind come from `skillstar_usage::subscription`.
//   - CatalogEntry, Subscription, SubscriptionAlert, SwitchOutcome, LinkMode,
//     CliAccountState, UsageSummary, MonthlySpendEntry, OAuthStart,
//     CreateSubscriptionInput,
//     UpdateSubscriptionInput are the DTO projections owned by
//     `skillstar_app::usage::dto` (their Rust names carry a `Dto` suffix that
//     `#[ts(rename)]` drops — on this side they are the only shapes).
//
// Only genuinely frontend-owned things stay hand-written below: the
// dialog's auth-mode filter, the active-account event contract, and the
// sidebar filter sentinel. None of those have a Rust counterpart.

export type { AuthMode } from "@/types/generated/AuthMode";
export type { CatalogTier } from "@/types/generated/CatalogTier";
export type { BillingCycle } from "@/types/generated/BillingCycle";
export type { AlertSeverity } from "@/types/generated/AlertSeverity";
export type { AlertKind } from "@/types/generated/AlertKind";

export type { CatalogEntry } from "@/types/generated/CatalogEntry";
export type { ManualQuota } from "@/types/generated/ManualQuota";
export type { UsageWindow } from "@/types/generated/UsageWindow";
export type { MonetaryBalance } from "@/types/generated/MonetaryBalance";
export type { CreditInfo } from "@/types/generated/CreditInfo";
export type { OpenCodeApiKey } from "@/types/generated/OpenCodeApiKey";
export type { DeepSeekModelUsage } from "@/types/generated/DeepSeekModelUsage";
export type { DeepSeekDailyUsage } from "@/types/generated/DeepSeekDailyUsage";
export type { DeepSeekAnalytics } from "@/types/generated/DeepSeekAnalytics";
export type { SubscriptionUsage } from "@/types/generated/SubscriptionUsage";

export type { Subscription } from "@/types/generated/Subscription";
export type { SwitchOutcome } from "@/types/generated/SwitchOutcome";
export type { LinkMode } from "@/types/generated/LinkMode";
export type { CliAccountState } from "@/types/generated/CliAccountState";
export type { CreateSubscriptionInput } from "@/types/generated/CreateSubscriptionInput";
export type { UpdateSubscriptionInput } from "@/types/generated/UpdateSubscriptionInput";
export type { SubscriptionAlert } from "@/types/generated/SubscriptionAlert";
export type { MonthlySpendEntry } from "@/types/generated/MonthlySpendEntry";
export type { UsageSummary } from "@/types/generated/UsageSummary";
export type { OAuthStart } from "@/types/generated/OAuthStart";

/** Catalog ids that support `import_subscription_from_local`. */
export const LOCAL_IMPORT_CATALOG_IDS = ["codex", "antigravity", "cursor"] as const;

/** Backend broadcast when a catalog's active account changes. */
export const USAGE_ACTIVE_CHANGED_EVENT = "usage://active-changed";

/** Payload of {@link USAGE_ACTIVE_CHANGED_EVENT}. */
export interface ActiveChangedPayload {
  catalogId: string;
  subscriptionId: string;
}

/** Sidebar selection: "all" | a specific catalog id. */
export type CatalogFilter = string;
export const FILTER_ALL: CatalogFilter = "__all__";
